train_file: ['./pretrain_data/json_pretrain/coco.json',
             './pretrain_data/json_pretrain/vg.json',
             ]
laion_path: ''   

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 1





